[package]
name = "tekst-receiver"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
egui = { version = "0.33.3", optional = true }
local-ip-address = "0.6.13"
rppal = "0.22.1"
serde = "1.0.228"
serde_json = "1.0.150"
tekst-common = { path = "../common", features = [ "egui" ] }


[features]
embedded = []
desktop = ["dep:egui"]

embedded-animations = []
