[package]
name = "tekst-receiver"
version.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
eframe = { version = "0.33.3", optional = true }
egui = { version = "0.33.3", optional = true }
local-ip-address = "0.6.13"
rppal = { version = "0.22.1", optional = true } 
serde = "1.0.228"
serde_json = "1.0.150"
tekst-common = { path = "../common", features = [ "egui" ] }


[features]
default = ["desktop", "startup-checks"]
embedded = ["dep:rppal", "startup-checks"]
desktop = ["dep:egui", "dep:eframe"]
startup-checks = []
