[package]
name = "tekst"
version.workspace = true
repository.workspace = true
edition.workspace = true

[package.metadata.wix]
upgrade-guid = "43CC461F-B6B8-4BAE-9047-0D6678789184"
path-guid = "43FE3284-EE24-4A48-B85A-095883C2B768"
license = false
eula = false

[dependencies]
csv = "1.4.0"
eframe = { version = "0.33.3", features = ["persistence"] }
egui = { version = "0.33.3", features = ["persistence", "serde"] }
egui-file-dialog = "0.12.0"
egui-keybind = { version = "0.8.0", features = ["serde"] }
egui_table = "0.7.0"
hound = "3.5.1"
rodio = "0.22.2"
serde = { version = "1.0.228", features = ["serde_derive"] }
ks-common-ui = { git = "https://github.com/lexag/ks-common", branch="ui-framework" }
#ks-common-ui = { path = "../clicks/common/ui" } 
ks-common-generic = { git = "https://github.com/lexag/ks-common", branch="release/v2.3.0", features = ["serde"] } 
tekst-common = { path = "../common", features = ["egui"] }
serde_json = "1.0.150"
