[package]
name = "tekst-common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
egui = { version = "0.35.0", optional = true }

ks-common-ui = { git = "https://github.com/lexag/ks-common", branch="ui-framework", optional = true }
ks-common-generic = { git = "https://github.com/lexag/ks-common", branch="release/v2.3.0", features = ["serde"] } 

[features]
egui = ["dep:egui", "dep:ks-common-ui"]
