[package]
name = "tekst-common"
version.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"

ks-common-ui = { git = "https://github.com/lexag/ks-common", optional = true }
ks-common-generic = { git = "https://github.com/lexag/ks-common", version="2.3.0", features = ["serde"] } 

cosmic-text = { version = "0.19.0", optional = true }
egui = { version = "0.33.3", optional = true }

[features]
egui = ["dep:egui", "dep:ks-common-ui"]
rasterizer = ["dep:cosmic-text"]
